In [1]:
import numpy as np

In [2]:
arr = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]
arr = np.array(arr)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [3]:
q = arr[:,:,[True,False,True]]
q

array([[[ 1,  3],
        [ 4,  6]],

       [[ 7,  9],
        [10, 12]],

       [[13, 15],
        [16, 18]]])

In [4]:
p = np.array([1,1,0])
p

array([1, 1, 0])

In [5]:
h = p==1
print(h)
q = arr[:,:,h]
q

[ True  True False]


array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]],

       [[13, 14],
        [16, 17]]])

In [6]:
sum(h)

2