In [29]:
import pandas as pd
import numpy as np
import glob, os
import time
import pickle
import matplotlib.pyplot as plt
import math
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, TimeDistributed
from keras.layers import LSTM, GRU
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from keras.optimizers import SGD

#np.seed(7)

with open('finalset/preprocess_48_hours.pickle', 'rb') as handle:
    [X,  Y] = pickle.load(handle)
df_murda = Y['LABEL']==1
df_murda = df_murda.as_matrix()
Y.drop(['SUBJECT_ID'],1, inplace=True)
Y = np.array(Y)
print(len(X),len(Y))
print(X.shape)
print(Y.shape)
X_murda = X[df_murda]
X_murda = np.repeat(X_murda,1,axis=0)
X = np.concatenate((X,X_murda),axis=0)
print(X.shape)
Y_murda = Y[df_murda]
Y_murda = np.repeat(Y_murda,1,axis=0)
Y = np.concatenate((Y,Y_murda),axis=0)
Y.shape

6587 6587
(6587, 49, 37)
(6587, 1)
(9048, 49, 37)


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:20: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


(9048, 1)

In [30]:
X_new = X.reshape(X.shape[0],1,X.shape[1],X.shape[2])
Y_new = Y.reshape(Y.shape[0],1,Y.shape[1])
print(Y_new.shape)
X_new = np.insert(X_new, 1, Y_new, axis=1)
np.random.shuffle(X_new)
X_new.shape

(9048, 1, 1)


(9048, 2, 49, 37)

In [31]:
X = X_new[:,0]

X.shape

(9048, 49, 37)

In [32]:
Y = X_new[:,1]
Y = Y[:,0]
Y = Y[:,0]
Y = Y.reshape(Y.shape[0],1)
Y.shape

(9048, 1)

In [33]:
X = (X-np.mean(X))/(np.std(X))
X.shape

(9048, 49, 37)

In [34]:
from sklearn.model_selection import StratifiedShuffleSplit
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=2)
sss.get_n_splits(X, Y)

for train_index, test_index in sss.split(X, Y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    train_X, test1_X = X[train_index], X[test_index]
    train_Y, test1_Y = Y[train_index], Y[test_index]

In [35]:
sss1 = StratifiedShuffleSplit(n_splits=1, test_size=0.5, random_state=0)
sss1.get_n_splits(test1_X, test1_Y)

for test_index, val_index in sss1.split(test1_X, test1_Y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    test_X, val_X = test1_X[test_index], test1_X[val_index]
    test_Y, val_Y = test1_Y[test_index], test1_Y[val_index]

In [36]:
print(train_X.shape, test_X.shape, train_Y.shape, test_Y.shape, val_X.shape, val_Y.shape)

(6333, 49, 37) (1357, 49, 37) (6333, 1) (1357, 1) (1358, 49, 37) (1358, 1)


In [37]:
print(len(train_X), len(test_X))
print(len(train_Y), len(test_Y))

6333 1357
6333 1357


In [38]:
# lstm_size = []
# drpout = []
# dense1 = []
# dense2 = []
# dense3 = []

# # create and fit the LSTM network
# model = Sequential()
# model.add(LSTM(27, return_sequences = True, input_dim = 37, input_length = 49))
# model.add(Dropout(0.5))
# print model.output_shape
# #model.add(LSTM(14, return_sequences = True))
# #model.add(Dropout(0.5))
# model.add(Flatten())
# print model.output_shape
# model.add(Dense(100, init='glorot_uniform', activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(10, init='glorot_uniform', activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(5, init='glorot_uniform', activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(1, init='glorot_uniform', activation='sigmoid'))
# model.compile(loss='binary_crossentropy', optimizer='RMSprop', metrics=['accuracy'])
# model.fit(train_X, train_Y, nb_epoch=100, batch_size=40, verbose=2)
# val_predict = model.predict(val_X,  batch_size=40)
# from sklearn.metrics import roc_auc_score
# roc_auc_score(val_Y, val_predict)

In [ ]:
from sklearn.metrics import mean_squared_error
from hyperopt import fmin, tpe, hp, STATUS_OK, Trials
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import StratifiedKFold
import pandas as pd;
import numpy as np;
from sklearn import model_selection

best_params = None
best_score = 1000
auc = None
model_final = None
def score(params):
    global best_score
    global best_params
    global auc
    global model_final
    print("Training with params : ")
    print(params)
    lstm_size = params['lstm_size']
    attention = params['attention']
    dropout = params['dropout']
    dense1 = params['dense1']
    dense2 = params['dense2']
    dense3 = params['dense3']

    
    model = Sequential()
    model.add(LSTM(lstm_size, return_sequences = True, input_dim = 37, input_length = 49))
    model.add(TimeDistributed(Dense(attention, activation='tanh')))
    #model.add(Dropout(dropout))
    #print model.output_shape
    #model.add(LSTM(14, return_sequences = True))
    #model.add(Dropout(0.5))
    model.add(Flatten())
    #print model.output_shape
    model.add(Dense(dense1, init='glorot_uniform', activation='relu'))
    model.add(Dropout(dropout))
    model.add(Dense(dense2, init='glorot_uniform', activation='relu'))
    model.add(Dropout(dropout))
    model.add(Dense(dense3, init='glorot_uniform', activation='relu'))
    model.add(Dropout(dropout))
    model.add(Dense(1, init='glorot_uniform', activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='RMSprop', metrics=['accuracy'])
    model.fit(train_X, train_Y, nb_epoch=1, batch_size=40, verbose=0)
    val_predict = model.predict(val_X,  batch_size=40)
    test_predict=model.predict(test_X,batch_size=40)
    from sklearn.metrics import roc_auc_score, f1_score,precision_recall_fscore_support
    from sklearn.metrics import confusion_matrix
    score = 1.0 - roc_auc_score(val_Y, val_predict)
    f_score=f1_score(test_Y,test_predict.round())
    prfs=precision_recall_fscore_support(test_Y,test_predict.round())
    f_score_micro=f1_score(test_Y,test_predict.round(),average='micro')
    f_score_macro=f1_score(test_Y,test_predict.round(),average='macro')
    cf=confusion_matrix(test_Y,test_predict.round())
    #scores = model_selection.cross_val_score(model, X, y, scoring='roc_auc', cv=sss, n_jobs=-1, verbose=0)
    #score = 1.0-scores.mean()
    if best_score > score:
        best_score = score
        best_params = params
        auc = 1.0 - score
        model_final = model
    print("AUC : "+str(1.0 - score)+",  Score/Loss : "+str(score)+", F1_Score_average: "+str(f_score)+", Precision, Recall, F1_score, Support: "+str(prfs))
    print("F1_score_micro: "+str(f_score_micro))
    print("F1_score_macro: "+str(f_score_macro))
    print("Confusion Matrix")
    print(cf)
    print("END\n\n")
    return {'loss': score, 'status': STATUS_OK}

def optimize(trials):
    space = {
    'lstm_size': hp.choice('lstm_size', np.arange(15, 35, 5, dtype=int)),
    'attention': hp.choice('attention',[10, 20, 30, 40]),  
    'dropout': hp.choice('dropout',[0.5, 0.3]),
    'dense1': hp.choice('dense1', [70, 80, 90, 100, 125]),
    'dense2' : hp.choice('dense2', np.arange(8, 20, 3, dtype=int)),
    "dense3": hp.choice('dense3', np.arange(5, 8, 1, dtype=int))
    }
    best = fmin(score, space, algo=tpe.suggest, trials=trials, max_evals=40)
    #print "optimize best", best
    return best



# from sklearn import datasets
# iris = datasets.load_iris()
# iris_X = iris.data
# iris_y = iris.target
# #print set(iris_y)

# X, y = iris_X,iris_y
# y[y[:] == 2] = 1
# y[y[:] == 3] = 2

# #print set(y)
# #print "Splitting data into train and valid ...\n\n"
# sss = StratifiedKFold(y, n_folds=3,shuffle=True, random_state=42)

# #Trials object where the history of search will be stored
trials = Trials()
best = optimize(trials)
#print "best", best
print("best_score : ", best_score)
print("best_params\n\n", best_params)
print("\n\nauc : ", auc)

Training with params : 
{'attention': 10, 'dropout': 0.3, 'dense3': 6, 'dense1': 90, 'lstm_size': 15, 'dense2': 14}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(15, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(90, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(14, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

AUC : 0.5625392127072126,  Score/Loss : 0.43746078729278737, F1_Score_average: 0.6958230958230958, Precision, Recall, F1_score, Support: (array([0.5      , 0.5458751]), array([0.04846527, 0.95934959]), array([0.08836524, 0.6958231 ]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.392094169413757
Confusion Matrix
[[ 30 589]
 [ 30 708]]
END


Training with params : 
{'attention': 40, 'dropout': 0.3, 'dense3': 7, 'dense1': 90, 'lstm_size': 25, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(25, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(90, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

AUC : 0.5532013964642435,  Score/Loss : 0.4467986035357565, F1_Score_average: 0.669050051072523, Precision, Recall, F1_score, Support: (array([0.39416058, 0.53688525]), array([0.08723748, 0.88753388]), array([0.14285714, 0.66905005]), array([619, 738]))
F1_score_micro: 0.522476050110538
F1_score_macro: 0.40595359696483296
Confusion Matrix
[[ 54 565]
 [ 83 655]]
END


Training with params : 
{'attention': 40, 'dropout': 0.3, 'dense3': 5, 'dense1': 100, 'lstm_size': 30, 'dense2': 11}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(30, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(100, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5099542891870208,  Score/Loss : 0.4900457108129792, F1_Score_average: 0.7036859741503112, Precision, Recall, F1_score, Support: (array([0.5       , 0.54404145]), array([0.00484653, 0.99593496]), array([0.0096    , 0.70368597]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.3566429870751556
Confusion Matrix
[[  3 616]
 [  3 735]]
END


Training with params : 
{'attention': 30, 'dropout': 0.3, 'dense3': 6, 'dense1': 100, 'lstm_size': 20, 'dense2': 14}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(100, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(14, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5503452904308971,  Score/Loss : 0.4496547095691029, F1_Score_average: 0.7037392138063279, Precision, Recall, F1_score, Support: (array([0.55555556, 0.54451039]), array([0.00807754, 0.99457995]), array([0.01592357, 0.70373921]), array([619, 738]))
F1_score_micro: 0.5445836403831983
F1_score_macro: 0.3598313903426544
Confusion Matrix
[[  5 614]
 [  4 734]]
END


Training with params : 
{'attention': 40, 'dropout': 0.3, 'dense3': 6, 'dense1': 125, 'lstm_size': 20, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5745178066679638,  Score/Loss : 0.4254821933320362, F1_Score_average: 0.7030420086914534, Precision, Recall, F1_score, Support: (array([0.58333333, 0.54613653]), array([0.02261712, 0.98644986]), array([0.04354588, 0.70304201]), array([619, 738]))
F1_score_micro: 0.5467943994104643
F1_score_macro: 0.3732939436925385
Confusion Matrix
[[ 14 605]
 [ 10 728]]
END


Training with params : 
{'attention': 10, 'dropout': 0.3, 'dense3': 5, 'dense1': 70, 'lstm_size': 20, 'dense2': 14}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(70, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(14, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

AUC : 0.5610122398298361,  Score/Loss : 0.43898776017016394, F1_Score_average: 0.7045346062052505, Precision, Recall, F1_score, Support: (array([0.        , 0.54384672]), array([0., 1.]), array([0.        , 0.70453461]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.3522673031026253
Confusion Matrix
[[  0 619]
 [  0 738]]
END


Training with params : 
{'attention': 10, 'dropout': 0.5, 'dense3': 6, 'dense1': 100, 'lstm_size': 20, 'dense2': 14}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(14, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:43: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:45: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
/home/yoda/.local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/y

AUC : 0.5369982139773217,  Score/Loss : 0.4630017860226783, F1_Score_average: 0.7045346062052505, Precision, Recall, F1_score, Support: (array([0.        , 0.54384672]), array([0., 1.]), array([0.        , 0.70453461]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.3522673031026253
Confusion Matrix
[[  0 619]
 [  0 738]]
END


Training with params : 
{'attention': 30, 'dropout': 0.3, 'dense3': 5, 'dense1': 70, 'lstm_size': 25, 'dense2': 14}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(70, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(14, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:43: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:45: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


AUC : 0.5571734934122652,  Score/Loss : 0.4428265065877348, F1_Score_average: 0.6849315068493151, Precision, Recall, F1_score, Support: (array([0.49193548, 0.54744526]), array([0.09854604, 0.91463415]), array([0.16419919, 0.68493151]), array([619, 738]))
F1_score_micro: 0.5423728813559322
F1_score_macro: 0.4245653496561515
Confusion Matrix
[[ 61 558]
 [ 63 675]]
END


Training with params : 
{'attention': 40, 'dropout': 0.3, 'dense3': 5, 'dense1': 90, 'lstm_size': 15, 'dense2': 8}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(15, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(90, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.

AUC : 0.4972695932371607,  Score/Loss : 0.5027304067628393, F1_Score_average: 0.7045346062052505, Precision, Recall, F1_score, Support: (array([0.        , 0.54384672]), array([0., 1.]), array([0.        , 0.70453461]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.3522673031026253
Confusion Matrix
[[  0 619]
 [  0 738]]
END


Training with params : 
{'attention': 40, 'dropout': 0.3, 'dense3': 6, 'dense1': 90, 'lstm_size': 30, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(90, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:43: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:45: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


AUC : 0.5652849219899397,  Score/Loss : 0.43471507801006026, F1_Score_average: 0.5921052631578947, Precision, Recall, F1_score, Support: (array([0.49913043, 0.57544757]), array([0.46365105, 0.6097561 ]), array([0.48073702, 0.59210526]), array([619, 738]))
F1_score_micro: 0.5431098010316876
F1_score_macro: 0.5364211407916777
Confusion Matrix
[[287 332]
 [288 450]]
END


Training with params : 
{'attention': 10, 'dropout': 0.3, 'dense3': 5, 'dense1': 100, 'lstm_size': 15, 'dense2': 11}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(15, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(100, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5699926329297111,  Score/Loss : 0.43000736707028886, F1_Score_average: 0.6983972802331229, Precision, Recall, F1_score, Support: (array([0.47222222, 0.54428463]), array([0.02746365, 0.97425474]), array([0.0519084 , 0.69839728]), array([619, 738]))
F1_score_micro: 0.5423728813559322
F1_score_macro: 0.3751528385898439
Confusion Matrix
[[ 17 602]
 [ 19 719]]
END


Training with params : 
{'attention': 40, 'dropout': 0.5, 'dense3': 5, 'dense1': 125, 'lstm_size': 25, 'dense2': 8}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(25, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

AUC : 0.5147352336148269,  Score/Loss : 0.48526476638517313, F1_Score_average: 0.7045346062052505, Precision, Recall, F1_score, Support: (array([0.        , 0.54384672]), array([0., 1.]), array([0.        , 0.70453461]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.3522673031026253
Confusion Matrix
[[  0 619]
 [  0 738]]
END


Training with params : 
{'attention': 10, 'dropout': 0.3, 'dense3': 5, 'dense1': 70, 'lstm_size': 20, 'dense2': 11}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(70, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:43: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:45: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
/home/yoda/.local/lib/python3.5/site-packages/sklearn/metrics/

AUC : 0.5631491274284552,  Score/Loss : 0.43685087257154476, F1_Score_average: 0.7045346062052505, Precision, Recall, F1_score, Support: (array([0.        , 0.54384672]), array([0., 1.]), array([0.        , 0.70453461]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.3522673031026253
Confusion Matrix
[[  0 619]
 [  0 738]]
END


Training with params : 
{'attention': 40, 'dropout': 0.3, 'dense3': 5, 'dense1': 90, 'lstm_size': 15, 'dense2': 14}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(90, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(14, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:43: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:45: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


AUC : 0.5348908383813431,  Score/Loss : 0.4651091616186569, F1_Score_average: 0.7048710601719198, Precision, Recall, F1_score, Support: (array([1.        , 0.54424779]), array([0.00161551, 1.        ]), array([0.00322581, 0.70487106]), array([619, 738]))
F1_score_micro: 0.5445836403831983
F1_score_macro: 0.35404843331176633
Confusion Matrix
[[  1 618]
 [  0 738]]
END


Training with params : 
{'attention': 20, 'dropout': 0.5, 'dense3': 7, 'dense1': 70, 'lstm_size': 20, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(70, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

AUC : 0.5514798629768648,  Score/Loss : 0.4485201370231352, F1_Score_average: 0.7048710601719198, Precision, Recall, F1_score, Support: (array([1.        , 0.54424779]), array([0.00161551, 1.        ]), array([0.00322581, 0.70487106]), array([619, 738]))
F1_score_micro: 0.5445836403831983
F1_score_macro: 0.35404843331176633
Confusion Matrix
[[  1 618]
 [  0 738]]
END


Training with params : 
{'attention': 30, 'dropout': 0.3, 'dense3': 5, 'dense1': 90, 'lstm_size': 25, 'dense2': 11}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(25, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(90, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

AUC : 0.5390334491224006,  Score/Loss : 0.4609665508775994, F1_Score_average: 0.7043478260869565, Precision, Recall, F1_score, Support: (array([0.64     , 0.5472973]), array([0.02584814, 0.98780488]), array([0.04968944, 0.70434783]), array([619, 738]))
F1_score_micro: 0.5490051584377302
F1_score_macro: 0.3770186335403726
Confusion Matrix
[[ 16 603]
 [  9 729]]
END


Training with params : 
{'attention': 40, 'dropout': 0.3, 'dense3': 5, 'dense1': 125, 'lstm_size': 30, 'dense2': 8}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(30, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

AUC : 0.5095422141871848,  Score/Loss : 0.4904577858128152, F1_Score_average: 0.5681969394544244, Precision, Recall, F1_score, Support: (array([0.47466216, 0.55816993]), array([0.453958  , 0.57859079]), array([0.46407927, 0.56819694]), array([619, 738]))
F1_score_micro: 0.5217391304347826
F1_score_macro: 0.5161381063911263
Confusion Matrix
[[281 338]
 [311 427]]
END


Training with params : 
{'attention': 10, 'dropout': 0.3, 'dense3': 5, 'dense1': 80, 'lstm_size': 30, 'dense2': 14}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(30, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(80, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(14, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

AUC : 0.562018927031027,  Score/Loss : 0.43798107296897304, F1_Score_average: 0.700587084148728, Precision, Recall, F1_score, Support: (array([0.56862745, 0.5482389 ]), array([0.04684976, 0.9701897 ]), array([0.08656716, 0.70058708]), array([619, 738]))
F1_score_micro: 0.5490051584377302
F1_score_macro: 0.3935771241639162
Confusion Matrix
[[ 29 590]
 [ 22 716]]
END


Training with params : 
{'attention': 10, 'dropout': 0.3, 'dense3': 5, 'dense1': 125, 'lstm_size': 20, 'dense2': 11}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5537828922199801,  Score/Loss : 0.4462171077800199, F1_Score_average: 0.6793227296049256, Precision, Recall, F1_score, Support: (array([0.47945205, 0.54665566]), array([0.11308562, 0.89701897]), array([0.18300654, 0.67932273]), array([619, 738]))
F1_score_micro: 0.5394252026529108
F1_score_macro: 0.431164632776319
Confusion Matrix
[[ 70 549]
 [ 76 662]]
END


Training with params : 
{'attention': 10, 'dropout': 0.3, 'dense3': 7, 'dense1': 80, 'lstm_size': 20, 'dense2': 14}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(80, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(14, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

AUC : 0.5436296702744179,  Score/Loss : 0.4563703297255821, F1_Score_average: 0.5834957764782327, Precision, Recall, F1_score, Support: (array([0.48021583, 0.56054931]), array([0.43134087, 0.60840108]), array([0.45446809, 0.58349578]), array([619, 738]))
F1_score_micro: 0.5276344878408253
F1_score_macro: 0.5189819307923078
Confusion Matrix
[[267 352]
 [289 449]]
END


Training with params : 
{'attention': 20, 'dropout': 0.5, 'dense3': 6, 'dense1': 100, 'lstm_size': 15, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(15, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(100, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5122278064274955,  Score/Loss : 0.48777219357250445, F1_Score_average: 0.7000964320154291, Precision, Recall, F1_score, Support: (array([0.42857143, 0.54341317]), array([0.01453958, 0.98373984]), array([0.028125  , 0.70009643]), array([619, 738]))
F1_score_micro: 0.5416359616801769
F1_score_macro: 0.36411071600771455
Confusion Matrix
[[  9 610]
 [ 12 726]]
END


Training with params : 
{'attention': 20, 'dropout': 0.5, 'dense3': 6, 'dense1': 125, 'lstm_size': 15, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(15, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5028156636593573,  Score/Loss : 0.49718433634064274, F1_Score_average: 0.6750503018108652, Precision, Recall, F1_score, Support: (array([0.37383178, 0.5368    ]), array([0.06462036, 0.90921409]), array([0.11019284, 0.6750503 ]), array([619, 738]))
F1_score_micro: 0.5239498894620487
F1_score_macro: 0.392621569638215
Confusion Matrix
[[ 40 579]
 [ 67 671]]
END


Training with params : 
{'attention': 40, 'dropout': 0.3, 'dense3': 6, 'dense1': 125, 'lstm_size': 15, 'dense2': 11}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(15, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5445937290273499,  Score/Loss : 0.4554062709726501, F1_Score_average: 0.7052631578947368, Precision, Recall, F1_score, Support: (array([0.8       , 0.54511834]), array([0.00646204, 0.99864499]), array([0.01282051, 0.70526316]), array([619, 738]))
F1_score_micro: 0.5460574797347089
F1_score_macro: 0.3590418353576248
Confusion Matrix
[[  4 615]
 [  1 737]]
END


Training with params : 
{'attention': 30, 'dropout': 0.3, 'dense3': 6, 'dense1': 100, 'lstm_size': 15, 'dense2': 11}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(15, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(100, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5625413987814822,  Score/Loss : 0.43745860121851776, F1_Score_average: 0.7045346062052505, Precision, Recall, F1_score, Support: (array([0.        , 0.54384672]), array([0., 1.]), array([0.        , 0.70453461]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.3522673031026253
Confusion Matrix
[[  0 619]
 [  0 738]]
END


Training with params : 
{'attention': 20, 'dropout': 0.3, 'dense3': 7, 'dense1': 125, 'lstm_size': 15, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:43: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:45: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


AUC : 0.5828030281500785,  Score/Loss : 0.41719697184992155, F1_Score_average: 0.5105386416861827, Precision, Recall, F1_score, Support: (array([0.495086  , 0.60220994]), array([0.65105008, 0.44308943]), array([0.56245639, 0.51053864]), array([619, 738]))
F1_score_micro: 0.5379513633014001
F1_score_macro: 0.5364975134460223
Confusion Matrix
[[403 216]
 [411 327]]
END


Training with params : 
{'attention': 20, 'dropout': 0.5, 'dense3': 7, 'dense1': 125, 'lstm_size': 20, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5202036984004494,  Score/Loss : 0.47979630159955056, F1_Score_average: 0.2984771573604061, Precision, Recall, F1_score, Support: (array([0.46756757, 0.5951417 ]), array([0.83844911, 0.19918699]), array([0.60034702, 0.29847716]), array([619, 738]))
F1_score_micro: 0.49078850405305824
F1_score_macro: 0.4494120893800295
Confusion Matrix
[[519 100]
 [591 147]]
END


Training with params : 
{'attention': 20, 'dropout': 0.3, 'dense3': 7, 'dense1': 125, 'lstm_size': 15, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(15, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5337606379839149,  Score/Loss : 0.46623936201608507, F1_Score_average: 0.7045346062052505, Precision, Recall, F1_score, Support: (array([0.        , 0.54384672]), array([0., 1.]), array([0.        , 0.70453461]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.3522673031026253
Confusion Matrix
[[  0 619]
 [  0 738]]
END


Training with params : 
{'attention': 20, 'dropout': 0.3, 'dense3': 7, 'dense1': 125, 'lstm_size': 20, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:43: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:45: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


AUC : 0.5692111113782978,  Score/Loss : 0.43078888862170217, F1_Score_average: 0.521875, Precision, Recall, F1_score, Support: (array([0.50429448, 0.61623616]), array([0.66397415, 0.45257453]), array([0.57322176, 0.521875  ]), array([619, 738]))
F1_score_micro: 0.5490051584377302
F1_score_macro: 0.5475483786610879
Confusion Matrix
[[411 208]
 [404 334]]
END


Training with params : 
{'attention': 20, 'dropout': 0.3, 'dense3': 7, 'dense1': 125, 'lstm_size': 15, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(15, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5592404266342546,  Score/Loss : 0.44075957336574545, F1_Score_average: 0.6943209876543209, Precision, Recall, F1_score, Support: (array([0.5       , 0.54623155]), array([0.05654281, 0.95257453]), array([0.10159652, 0.69432099]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.39795875217258864
Confusion Matrix
[[ 35 584]
 [ 35 703]]
END


Training with params : 
{'attention': 20, 'dropout': 0.5, 'dense3': 7, 'dense1': 80, 'lstm_size': 30, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(30, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(80, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

AUC : 0.5096176337494891,  Score/Loss : 0.4903823662505109, F1_Score_average: 0.7045346062052505, Precision, Recall, F1_score, Support: (array([0.        , 0.54384672]), array([0., 1.]), array([0.        , 0.70453461]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.3522673031026253
Confusion Matrix
[[  0 619]
 [  0 738]]
END


Training with params : 
{'attention': 40, 'dropout': 0.3, 'dense3': 6, 'dense1': 125, 'lstm_size': 25, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(6, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:43: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:45: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
/home/yoda/.local/lib/python3.5/site-packages/sklearn/metrics

AUC : 0.5621806965269838,  Score/Loss : 0.43781930347301623, F1_Score_average: 0.7045346062052505, Precision, Recall, F1_score, Support: (array([0.        , 0.54384672]), array([0., 1.]), array([0.        , 0.70453461]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.3522673031026253
Confusion Matrix
[[  0 619]
 [  0 738]]
END


Training with params : 
{'attention': 20, 'dropout': 0.3, 'dense3': 7, 'dense1': 125, 'lstm_size': 20, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:43: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:45: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


AUC : 0.6082675142805303,  Score/Loss : 0.3917324857194697, F1_Score_average: 0.6875310481867858, Precision, Recall, F1_score, Support: (array([0.43902439, 0.5427451 ]), array([0.05815832, 0.93766938]), array([0.10271041, 0.68753105]), array([619, 738]))
F1_score_micro: 0.5364775239498895
F1_score_macro: 0.3951207309407538
Confusion Matrix
[[ 36 583]
 [ 46 692]]
END


Training with params : 
{'attention': 20, 'dropout': 0.3, 'dense3': 7, 'dense1': 80, 'lstm_size': 15, 'dense2': 8}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(15, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(80, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.

AUC : 0.5179476697541322,  Score/Loss : 0.4820523302458678, F1_Score_average: 0.7043062200956938, Precision, Recall, F1_score, Support: (array([0.6      , 0.5443787]), array([0.00484653, 0.99728997]), array([0.00961538, 0.70430622]), array([619, 738]))
F1_score_micro: 0.5445836403831983
F1_score_macro: 0.3569608023555392
Confusion Matrix
[[  3 616]
 [  2 736]]
END


Training with params : 
{'attention': 20, 'dropout': 0.3, 'dense3': 7, 'dense1': 125, 'lstm_size': 20, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5833812447944107,  Score/Loss : 0.41661875520558933, F1_Score_average: 0.6264150943396227, Precision, Recall, F1_score, Support: (array([0.52475248, 0.58450704]), array([0.42810985, 0.67479675]), array([0.47153025, 0.62641509]), array([619, 738]))
F1_score_micro: 0.5622697126013264
F1_score_macro: 0.5489726717249714
Confusion Matrix
[[265 354]
 [240 498]]
END


Training with params : 
{'attention': 20, 'dropout': 0.3, 'dense3': 7, 'dense1': 125, 'lstm_size': 20, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5425431913623834,  Score/Loss : 0.4574568086376166, F1_Score_average: 0.7039159503342884, Precision, Recall, F1_score, Support: (array([0.        , 0.54351032]), array([0.        , 0.99864499]), array([0.        , 0.70391595]), array([619, 738]))
F1_score_micro: 0.5431098010316876
F1_score_macro: 0.3519579751671442
Confusion Matrix
[[  0 619]
 [  1 737]]
END


Training with params : 
{'attention': 20, 'dropout': 0.3, 'dense3': 7, 'dense1': 125, 'lstm_size': 20, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python

AUC : 0.5536954492491927,  Score/Loss : 0.4463045507508073, F1_Score_average: 0.7056567593480345, Precision, Recall, F1_score, Support: (array([0.77777778, 0.54599407]), array([0.01130856, 0.99728997]), array([0.02229299, 0.70565676]), array([619, 738]))
F1_score_micro: 0.5475313190862195
F1_score_macro: 0.3639748764893039
Confusion Matrix
[[  7 612]
 [  2 736]]
END


Training with params : 
{'attention': 30, 'dropout': 0.5, 'dense3': 7, 'dense1': 70, 'lstm_size': 20, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(70, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

AUC : 0.5354799853970238,  Score/Loss : 0.4645200146029762, F1_Score_average: 0.7045346062052505, Precision, Recall, F1_score, Support: (array([0.        , 0.54384672]), array([0., 1.]), array([0.        , 0.70453461]), array([619, 738]))
F1_score_micro: 0.5438467207074429
F1_score_macro: 0.3522673031026253
Confusion Matrix
[[  0 619]
 [  0 738]]
END


Training with params : 
{'attention': 20, 'dropout': 0.3, 'dense3': 7, 'dense1': 125, 'lstm_size': 20, 'dense2': 8}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:43: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:45: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


AUC : 0.521535017630689,  Score/Loss : 0.478464982369311, F1_Score_average: 0.6624605678233438, Precision, Recall, F1_score, Support: (array([0.44041451, 0.54123711]), array([0.13731826, 0.85365854]), array([0.20935961, 0.66246057]), array([619, 738]))
F1_score_micro: 0.52689756816507
F1_score_macro: 0.43591008686733695
Confusion Matrix
[[ 85 534]
 [108 630]]
END


Training with params : 
{'attention': 20, 'dropout': 0.3, 'dense3': 7, 'dense1': 90, 'lstm_size': 20, 'dense2': 17}


/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:37: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(90, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:39: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(17, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="relu", kernel_initializer="glorot_uniform")`
/home/yoda/.local/lib/python3

In [ ]:
test_predict = model_final.predict(test_X,  batch_size=40)
#print(test_predict.shape)
score = model_final.evaluate(test_X, test_Y, verbose=0)
print(score)
from sklearn.metrics import roc_auc_score
print(roc_auc_score(test_Y, test_predict))

In [15]:
from keras.models import load_model
model.save('model.h5')

In [27]:
model = Sequential()
model.add(LSTM(20, return_sequences = 20, input_dim = 37, input_length = 49))
model.add(Dropout(0.3))
#print model.output_shape
#model.add(LSTM(14, return_sequences = True))
#model.add(Dropout(0.5))
model.add(Flatten())
#print model.output_shape
model.add(Dense(125, init='glorot_uniform', activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(11, init='glorot_uniform', activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(7, init='glorot_uniform', activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(1, init='glorot_uniform', activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='RMSprop', metrics=['accuracy'])
model.fit(train_X, train_Y, nb_epoch=10, batch_size=40, verbose=1)
val_predict = model.predict(val_X,  batch_size=40)
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
test_predict = model.predict(test_X,  batch_size=40)

print(roc_auc_score(val_Y, val_predict))
print(roc_auc_score(test_Y, test_predict))

/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=20, input_shape=(49, 37))`
  
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
  if __name__ == '__main__':
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, activation="relu", kernel_initializer="glorot_uniform")`
  # This is added back by InteractiveShellApp.init_path()
/home/yoda/.local/lib/python3.5/site-packages/ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(

Epoch 1/10
5663/5663 [==============================] - 16s 3ms/step - loss: 0.6940 - acc: 0.5352
Epoch 2/10
5663/5663 [==============================] - 4s 780us/step - loss: 0.6846 - acc: 0.5400
Epoch 3/10
5663/5663 [==============================] - 4s 762us/step - loss: 0.6809 - acc: 0.5403
Epoch 4/10
5663/5663 [==============================] - 5s 851us/step - loss: 0.6842 - acc: 0.5430
Epoch 5/10
5663/5663 [==============================] - 5s 808us/step - loss: 0.6848 - acc: 0.5411
Epoch 6/10
5663/5663 [==============================] - 4s 774us/step - loss: 0.6814 - acc: 0.5476
Epoch 7/10
5663/5663 [==============================] - 4s 771us/step - loss: 0.6845 - acc: 0.5458
Epoch 8/10
5663/5663 [==============================] - 5s 866us/step - loss: 0.6811 - acc: 0.5418
Epoch 9/10
5663/5663 [==============================] - 5s 798us/step - loss: 0.6838 - acc: 0.5483
Epoch 10/10
5663/5663 [==============================] - 4s 772us/step - loss: 0.6818 - acc: 0.5524
0.55636920

In [28]:
test_predict = model.predict(test_X,  batch_size=40)
#print(test_predict.shape)
score = model.evaluate(test_X, test_Y, verbose=0)
print(score)
from sklearn.metrics import roc_auc_score
print(roc_auc_score(test_Y, test_predict))

[0.6829080685752228, 0.5560131796698594]
0.5509963433173097


In [11]:
model = Sequential()
model.add(LSTM(20, return_sequences = True, input_dim = 37, input_length = 49))
model.add(Dropout(0.5))
#print model.output_shape
#model.add(LSTM(14, return_sequences = True))
#model.add(Dropout(0.5))
model.add(Flatten())
#print model.output_shape
model.add(Dense(125, init='glorot_uniform', activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(11, init='glorot_uniform', activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(7, init='glorot_uniform', activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, init='glorot_uniform', activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='RMSprop', metrics=['accuracy'])
model.fit(train_X, train_Y, nb_epoch=100, batch_size=40, verbose=2)
val_predict = model.predict(val_X,  batch_size=40)
test_predict = model.predict(test_X,  batch_size=1)
# print test_predict
# test_out=model_final.predict_classes(test_X,batch_size=40)
# val_out=model.predict_classes(val_X,  batch_size=40)
from sklearn.metrics import roc_auc_score,f1_score,precision_recall_fscore_support
print "Accuracy on validation dataset:"
print roc_auc_score(val_Y,val_predict)
print "Accuracy on test dataset:"
print roc_auc_score(test_Y,test_predict)
for i in range(1,len(test_predict)):
    print "Patient "+str(i)+ " critical illness probability: "+str(test_predict[i][0])
# print precision_recall_fscore_support(test_Y,test_predict.round())
# print f1_score(test_Y,test_predict.round(),average='macro')
# print f1_score(test_Y,test_predict.round(),average='micro')

/home/iiitm/.local/lib/python2.7/site-packages/ipykernel_launcher.py:2: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  
/home/iiitm/.local/lib/python2.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=True, input_shape=(49, 37))`
  
/home/iiitm/.local/lib/python2.7/site-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(125, activation="relu", kernel_initializer="glorot_uniform")`
  if __name__ == '__main__':
/home/iiitm/.local/lib/python2.7/site-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, activation="relu", kernel_initializer="glorot_uniform")`
  # This is added back by InteractiveShellApp.init_path()
/home/iiitm/.local/lib/python2.7/site-packages/ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: 

Epoch 1/100
0s - loss: 0.7007 - acc: 0.5000
Epoch 2/100
0s - loss: 0.6520 - acc: 0.5000
Epoch 3/100
0s - loss: 0.6647 - acc: 0.6364
Epoch 4/100
0s - loss: 0.5765 - acc: 0.6364
Epoch 5/100
0s - loss: 0.7702 - acc: 0.6364
Epoch 6/100
0s - loss: 0.6653 - acc: 0.6818
Epoch 7/100
0s - loss: 0.7310 - acc: 0.6364
Epoch 8/100
0s - loss: 0.6079 - acc: 0.6364
Epoch 9/100
0s - loss: 0.6622 - acc: 0.6818
Epoch 10/100
0s - loss: 0.5511 - acc: 0.7727
Epoch 11/100
0s - loss: 0.6399 - acc: 0.7273
Epoch 12/100
0s - loss: 0.6586 - acc: 0.5455
Epoch 13/100
0s - loss: 0.6123 - acc: 0.6818
Epoch 14/100
0s - loss: 0.6352 - acc: 0.6364
Epoch 15/100
0s - loss: 0.5678 - acc: 0.6364
Epoch 16/100
0s - loss: 0.6097 - acc: 0.7273
Epoch 17/100
0s - loss: 0.6475 - acc: 0.7273
Epoch 18/100
0s - loss: 0.6234 - acc: 0.6818
Epoch 19/100
0s - loss: 0.6129 - acc: 0.6364
Epoch 20/100
0s - loss: 0.5391 - acc: 0.7273
Epoch 21/100
0s - loss: 0.5309 - acc: 0.7273
Epoch 22/100
0s - loss: 0.5764 - acc: 0.7273
Epoch 23/100
0s - l