In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os


# Any results you write to the current directory are saved as output.

In [2]:
import pandas as pd
import numpy as np
import glob, os, sys
import time
import pickle
import datetime

In [3]:
df = pd.read_csv('../finalset/patient_data_24_hours.csv')
df.head(50)

SUBJECT_ID                  TimeStamp  Albumin  Alk. Phosphate       ALT  \
0           17  0 days 00:00:00.000000000      0.0        0.000000  0.000000   
1           17  1 days 00:00:00.000000000      0.0        0.000000  0.000000   
2           17  0 days 23:00:00.000000000      0.0        0.000000  0.000000   
3           17  0 days 22:00:00.000000000      0.0        0.000000  0.000000   
4           17  0 days 21:00:00.000000000      0.0        0.000000  0.000000   
5           17  0 days 20:00:00.000000000      0.0        0.000000  0.000000   
6           17  0 days 19:00:00.000000000      0.0        0.000000  0.000000   
7           17  0 days 17:00:00.000000000      0.0        0.000000  0.000000   
8           17  0 days 16:00:00.000000000      0.0        0.000000  0.000000   
9           17  0 days 15:00:00.000000000      0.0        0.000000  0.000000   
10          17  0 days 14:00:00.000000000      0.0        0.000000  0.000000   
11          17  0 days 13:00:00.000000000      0.0        0.000000  0.000000   
12          17  0 days 18:00:00.000000000      0.0        0.000000  0.000000   
13          17  0 days 11:00:00.000000000      0.0        0.000000  0.000000   
14          17  0 days 12:00:00.000000000      0.0        0.000000  0.000000   
15          17  0 days 02:00:00.000000000      0.0        0.000000  0.000000   
16          17  0 days 03:00:00.000000000      0.0        0.000000  0.000000   
17          17  0 days 04:00:00.000000000      0.0        0.000000  0.000000   
18          17  0 days 05:00:00.000000000      0.0        0.000000  0.000000   
19          17  0 days 01:00:00.000000000      0.0        0.000000  0.000000   
20          17  0 days 07:00:00.000000000      0.0        0.000000  0.000000   
21          17  0 days 08:00:00.000000000      0.0        0.000000  0.000000   
22          17  0 days 09:00:00.000000000      0.0        0.000000  0.000000   
23          17  0 days 10:00:00.000000000      0.0        0.000000  0.000000   
24          17  0 days 06:00:00.000000000      0.0        0.000000  0.000000   
25          21  0 days 13:00:00.000000000      0.0        0.017775  0.016509   
26          21  0 days 14:00:00.000000000      0.0        0.017775  0.016509   
27          21  0 days 15:00:00.000000000      0.0        0.017775  0.016509   
28          21  0 days 16:00:00.000000000      0.0        0.017775  0.016509   
29          21  0 days 17:00:00.000000000      0.0        0.017775  0.016509   
30          21  0 days 21:00:00.000000000      0.0        0.017775  0.016509   
31          21  0 days 20:00:00.000000000      0.0        0.017775  0.016509   
32          21  0 days 22:00:00.000000000      0.0        0.017775  0.016509   
33          21  0 days 23:00:00.000000000      0.0        0.017775  0.016509   
34          21  1 days 00:00:00.000000000      0.0        0.017775  0.016509   
35          21  0 days 19:00:00.000000000      0.0        0.017775  0.016509   
36          21  0 days 12:00:00.000000000      0.0        0.017775  0.016509   
37          21  0 days 18:00:00.000000000      0.0        0.017775  0.016509   
38          21  0 days 10:00:00.000000000      0.0        0.017775  0.016509   
39          21  0 days 01:00:00.000000000      0.0        0.017775  0.016509   
40          21  0 days 02:00:00.000000000      0.0        0.017775  0.016509   
41          21  0 days 03:00:00.000000000      0.0        0.017775  0.016509   
42          21  0 days 04:00:00.000000000      0.0        0.017775  0.016509   
43          21  0 days 05:00:00.000000000      0.0        0.017775  0.016509   
44          21  0 days 00:00:00.000000000      0.0        0.017775  0.016509   
45          21  0 days 06:00:00.000000000      0.0        0.017775  0.016509   
46          21  0 days 09:00:00.000000000      0.0        0.017775  0.016509   
47          21  0 days 11:00:00.000000000      0.0        0.017775  0.016509   
48          21  0 days 07:00:00.000000000      0.0        0.017775  0.016509   
49  

In [4]:
matrix3D = np.array(df.drop(['SUBJECT_ID', 'TimeStamp'], 1))
matrix3D

array([[0.        , 0.        , 0.        , ..., 0.        , 0.02173913,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.04725898,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.04725898,
        0.        ],
       ...,
       [0.79032258, 0.        , 0.00266276, ..., 0.        , 0.01587902,
        0.        ],
       [0.79032258, 0.        , 0.00266276, ..., 0.        , 0.01039698,
        0.        ],
       [0.79032258, 0.        , 0.00266276, ..., 0.        , 0.01587902,
        0.        ]])

In [5]:
matrix3D.shape

(164675, 37)

In [6]:
matrix3D = np.array(matrix3D).reshape((6587, 25, 37))
matrix3D.shape

(6587, 25, 37)

In [7]:
g = []
for k in range(37):
    h = (sum(sum(matrix3D[:,:,k])))
    if int(h)==0:
        g.append(False)
    else:
        g.append(True)
g = np.array(g)
g

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True])

In [8]:
matrix3D = matrix3D[:,:,g]
matrix3D.shape

(6587, 25, 30)

In [9]:
outcomes = pd.read_csv('../finalset/outcomes.csv')
outcomes.head(10)

SUBJECT_ID  LABEL
0          17      0
1          21      0
2          23      0
3          34      0
4          36      1
5          61      0
6          68      1
7          85      0
8          94      0
9         103      1

In [10]:
Y = np.array(outcomes.drop(['SUBJECT_ID'], 1))
Y.shape

(6587, 1)

In [11]:
X = matrix3D
X.shape

(6587, 25, 30)

In [12]:
X_train = X[:5500]
X_test = X[5500:]
Y_train = Y[:5500]
Y_test = Y[5500:]
display(X_train.shape)
display(X_test.shape)
display(Y_train.shape)
display(Y_test.shape)

(5500, 25, 30)

(1087, 25, 30)

(5500, 1)

(1087, 1)

In [13]:
X_train[0][0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.06060606, 0.        , 0.01343284, 0.22073579, 1.        ,
       0.25      , 0.11111111, 0.        , 0.48644338, 0.50615114,
       0.43425076, 0.        , 0.27926421, 0.02637363, 0.77966102,
       0.42574257, 0.46706587, 0.08112211, 0.10311573, 0.14356436,
       0.99009901, 0.44548872, 0.        , 0.02173913, 0.        ])

In [14]:
X_train[0][1]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05555556, 0.        , 0.01268657, 0.17725753, 0.75      ,
       1.        , 0.08353034, 0.        , 0.54066987, 0.42706503,
       0.4587156 , 0.        , 0.23076923, 0.02637363, 0.79661017,
       0.40594059, 0.33932136, 0.08247525, 0.1772997 , 0.24752475,
       0.99009901, 0.38721805, 0.        , 0.04725898, 0.        ])

In [15]:
X_train.shape

(5500, 25, 30)

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM,Add
from keras.layers import Dropout,Bidirectional,BatchNormalization,Conv2D,Conv1D
from keras.layers import Reshape,MaxPooling1D,Conv1D

Using TensorFlow backend.


In [17]:
model8ecw = Sequential()
model8ecw.add(Conv1D(32, kernel_size=5, input_shape=(X_train.shape[1],X_train.shape[2]), activation='tanh', padding='same',data_format="channels_last"))
model8ecw.add(Conv1D(32, 5, activation='tanh', padding='same'))
model8ecw.add(Conv1D(64, 5, activation='tanh', padding='same'))
model8ecw.add(MaxPooling1D(pool_size=2, data_format="channels_first"))
print(model8ecw.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1 (Conv1D)            (None, 25, 32)            4832      
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 25, 32)            5152      
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 25, 64)            10304     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 25, 32)            0         
Total params: 20,288
Trainable params: 20,288
Non-trainable params: 0
_________________________________________________________________
None


In [23]:
import keras.backend as K
channels = 5
steps = 4
filters = 3
val = np.array([list(range(i * channels, (i + 1) * channels)) for i in range(1, steps + 1)])
val = np.expand_dims(val, axis=0)
x = K.variable(value=val)

In [29]:
xtr = K.variable(value=X_train)

In [30]:
xtr.shape

TensorShape([Dimension(5500), Dimension(25), Dimension(30)])

In [31]:
xte = K.variable(value=X_test)

In [32]:
xte.shape

TensorShape([Dimension(1087), Dimension(25), Dimension(30)])

In [33]:
m1 = Conv1D(32, kernel_size=5, input_shape=(X_train.shape[1],X_train.shape[2]), activation='tanh', padding='same',data_format="channels_last")(xtr)
m1 = Conv1D(32, 5, activation='tanh', padding='same')(m1)
m1 = Conv1D(64, 5, activation='tanh', padding='same')(m1)
m1 = MaxPooling1D(pool_size=2, data_format="channels_first")(m1)

In [36]:
import keras.backend as K
w = K.eval(m1)

In [39]:
display(w[0][0])
X_train[0][0]

array([ 0.20673853, -0.01386446, -0.02197751,  0.07617988,  0.06157353,
       -0.02275016,  0.2340836 , -0.10696853,  0.10600666,  0.16745265,
       -0.06705421, -0.01936689,  0.06315036,  0.16780628,  0.07652007,
        0.3663451 ,  0.15699556, -0.03435377,  0.09315926,  0.18752116,
       -0.03516128, -0.01702615, -0.08716306,  0.2336611 , -0.11898301,
        0.1181429 ,  0.07396123,  0.15912849,  0.01502319,  0.21380283,
        0.25876072, -0.0272579 ], dtype=float32)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.06060606, 0.        , 0.01343284, 0.22073579, 1.        ,
       0.25      , 0.11111111, 0.        , 0.48644338, 0.50615114,
       0.43425076, 0.        , 0.27926421, 0.02637363, 0.77966102,
       0.42574257, 0.46706587, 0.08112211, 0.10311573, 0.14356436,
       0.99009901, 0.44548872, 0.        , 0.02173913, 0.        ])

In [38]:
w.shape

(5500, 25, 32)

In [40]:
m2 = Conv1D(32, kernel_size=5, input_shape=(X_train.shape[1],X_train.shape[2]), activation='tanh', padding='same',data_format="channels_last")(xte)
m2 = Conv1D(32, 5, activation='tanh', padding='same')(m2)
m2 = Conv1D(64, 5, activation='tanh', padding='same')(m2)
m2 = MaxPooling1D(pool_size=2, data_format="channels_first")(m2)

In [41]:
p = K.eval(m2)

In [43]:
p.shape

(1087, 25, 32)

In [42]:
display(p[0][0])
X_test[0][0]

array([ 0.00900122,  0.03684816, -0.04118307,  0.13839553,  0.06627423,
        0.08148471,  0.04361232, -0.0056854 ,  0.02708835, -0.00665865,
       -0.01033752,  0.09124018,  0.02795173, -0.02925631,  0.01702242,
       -0.0049729 ,  0.08946063,  0.0569252 , -0.06675359,  0.0003217 ,
        0.01435952,  0.03496999,  0.00902945,  0.0881175 , -0.00945816,
       -0.06645005,  0.05758869, -0.04290257, -0.06723458,  0.06694342,
        0.02322126,  0.0322963 ], dtype=float32)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08585859, 0.        , 0.01641791, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.45869947,
       0.        , 0.11428571, 0.        , 0.02747253, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.24752475,
       0.        , 0.        , 0.        , 0.03024575, 0.        ])