In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os


# Any results you write to the current directory are saved as output.

In [2]:
import pandas as pd
import numpy as np
import glob, os, sys
import time
import pickle
import datetime

In [3]:
df = pd.read_csv('../finalset/patient_data_24_hours.csv')
df.head(50)

SUBJECT_ID                  TimeStamp  Albumin  Alk. Phosphate       ALT  \
0           17  0 days 00:00:00.000000000      0.0        0.000000  0.000000   
1           17  1 days 00:00:00.000000000      0.0        0.000000  0.000000   
2           17  0 days 23:00:00.000000000      0.0        0.000000  0.000000   
3           17  0 days 22:00:00.000000000      0.0        0.000000  0.000000   
4           17  0 days 21:00:00.000000000      0.0        0.000000  0.000000   
5           17  0 days 20:00:00.000000000      0.0        0.000000  0.000000   
6           17  0 days 19:00:00.000000000      0.0        0.000000  0.000000   
7           17  0 days 17:00:00.000000000      0.0        0.000000  0.000000   
8           17  0 days 16:00:00.000000000      0.0        0.000000  0.000000   
9           17  0 days 15:00:00.000000000      0.0        0.000000  0.000000   
10          17  0 days 14:00:00.000000000      0.0        0.000000  0.000000   
11          17  0 days 13:00:00.000000000      0.0        0.000000  0.000000   
12          17  0 days 18:00:00.000000000      0.0        0.000000  0.000000   
13          17  0 days 11:00:00.000000000      0.0        0.000000  0.000000   
14          17  0 days 12:00:00.000000000      0.0        0.000000  0.000000   
15          17  0 days 02:00:00.000000000      0.0        0.000000  0.000000   
16          17  0 days 03:00:00.000000000      0.0        0.000000  0.000000   
17          17  0 days 04:00:00.000000000      0.0        0.000000  0.000000   
18          17  0 days 05:00:00.000000000      0.0        0.000000  0.000000   
19          17  0 days 01:00:00.000000000      0.0        0.000000  0.000000   
20          17  0 days 07:00:00.000000000      0.0        0.000000  0.000000   
21          17  0 days 08:00:00.000000000      0.0        0.000000  0.000000   
22          17  0 days 09:00:00.000000000      0.0        0.000000  0.000000   
23          17  0 days 10:00:00.000000000      0.0        0.000000  0.000000   
24          17  0 days 06:00:00.000000000      0.0        0.000000  0.000000   
25          21  0 days 13:00:00.000000000      0.0        0.017775  0.016509   
26          21  0 days 14:00:00.000000000      0.0        0.017775  0.016509   
27          21  0 days 15:00:00.000000000      0.0        0.017775  0.016509   
28          21  0 days 16:00:00.000000000      0.0        0.017775  0.016509   
29          21  0 days 17:00:00.000000000      0.0        0.017775  0.016509   
30          21  0 days 21:00:00.000000000      0.0        0.017775  0.016509   
31          21  0 days 20:00:00.000000000      0.0        0.017775  0.016509   
32          21  0 days 22:00:00.000000000      0.0        0.017775  0.016509   
33          21  0 days 23:00:00.000000000      0.0        0.017775  0.016509   
34          21  1 days 00:00:00.000000000      0.0        0.017775  0.016509   
35          21  0 days 19:00:00.000000000      0.0        0.017775  0.016509   
36          21  0 days 12:00:00.000000000      0.0        0.017775  0.016509   
37          21  0 days 18:00:00.000000000      0.0        0.017775  0.016509   
38          21  0 days 10:00:00.000000000      0.0        0.017775  0.016509   
39          21  0 days 01:00:00.000000000      0.0        0.017775  0.016509   
40          21  0 days 02:00:00.000000000      0.0        0.017775  0.016509   
41          21  0 days 03:00:00.000000000      0.0        0.017775  0.016509   
42          21  0 days 04:00:00.000000000      0.0        0.017775  0.016509   
43          21  0 days 05:00:00.000000000      0.0        0.017775  0.016509   
44          21  0 days 00:00:00.000000000      0.0        0.017775  0.016509   
45          21  0 days 06:00:00.000000000      0.0        0.017775  0.016509   
46          21  0 days 09:00:00.000000000      0.0        0.017775  0.016509   
47          21  0 days 11:00:00.000000000      0.0        0.017775  0.016509   
48          21  0 days 07:00:00.000000000      0.0        0.017775  0.016509   
49  

In [4]:
matrix3D = np.array(df.drop(['SUBJECT_ID', 'TimeStamp'], 1))
matrix3D

array([[0.        , 0.        , 0.        , ..., 0.        , 0.02173913,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.04725898,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.04725898,
        0.        ],
       ...,
       [0.79032258, 0.        , 0.00266276, ..., 0.        , 0.01587902,
        0.        ],
       [0.79032258, 0.        , 0.00266276, ..., 0.        , 0.01039698,
        0.        ],
       [0.79032258, 0.        , 0.00266276, ..., 0.        , 0.01587902,
        0.        ]])

In [5]:
matrix3D.shape

(164675, 37)

In [6]:
matrix3D = np.array(matrix3D).reshape((6587, 25, 37))
matrix3D.shape

(6587, 25, 37)

In [7]:
g = []
for k in range(37):
    h = (sum(sum(matrix3D[:,:,k])))
    if int(h)==0:
        g.append(False)
    else:
        g.append(True)
g = np.array(g)
g

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True])

In [8]:
matrix3D = matrix3D[:,:,g]
matrix3D.shape

(6587, 25, 30)

In [9]:
outcomes = pd.read_csv('../finalset/outcomes.csv')
outcomes.head(10)

SUBJECT_ID  LABEL
0          17      0
1          21      0
2          23      0
3          34      0
4          36      1
5          61      0
6          68      1
7          85      0
8          94      0
9         103      1

In [10]:
Y = np.array(outcomes.drop(['SUBJECT_ID'], 1))
Y.shape

(6587, 1)

In [11]:
X = matrix3D
X.shape

(6587, 25, 30)

In [12]:
X_train = X[:5500]
X_test = X[5500:]
Y_train = Y[:5500]
Y_test = Y[5500:]
display(X_train.shape)
display(X_test.shape)
display(Y_train.shape)
display(Y_test.shape)

(5500, 25, 30)

(1087, 25, 30)

(5500, 1)

(1087, 1)

In [13]:
X_train[0][0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.06060606, 0.        , 0.01343284, 0.22073579, 1.        ,
       0.25      , 0.11111111, 0.        , 0.48644338, 0.50615114,
       0.43425076, 0.        , 0.27926421, 0.02637363, 0.77966102,
       0.42574257, 0.46706587, 0.08112211, 0.10311573, 0.14356436,
       0.99009901, 0.44548872, 0.        , 0.02173913, 0.        ])

In [14]:
X_train[0][1]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05555556, 0.        , 0.01268657, 0.17725753, 0.75      ,
       1.        , 0.08353034, 0.        , 0.54066987, 0.42706503,
       0.4587156 , 0.        , 0.23076923, 0.02637363, 0.79661017,
       0.40594059, 0.33932136, 0.08247525, 0.1772997 , 0.24752475,
       0.99009901, 0.38721805, 0.        , 0.04725898, 0.        ])

In [15]:
X_train.shape

(5500, 25, 30)

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM,Add
from keras.layers import Dropout,Bidirectional,BatchNormalization,Conv2D,Conv1D
from keras.layers import Reshape,MaxPooling1D,Conv1D

Using TensorFlow backend.


In [17]:
model8ecw = Sequential()
model8ecw.add(Conv1D(32, kernel_size=5, input_shape=(X_train.shape[1],X_train.shape[2]), activation='tanh', padding='same',data_format="channels_last"))
model8ecw.add(Conv1D(32, 5, activation='tanh', padding='same'))
model8ecw.add(Conv1D(64, 5, activation='tanh', padding='same'))
model8ecw.add(MaxPooling1D(pool_size=2, data_format="channels_first"))
print(model8ecw.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1 (Conv1D)            (None, 25, 32)            4832      
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 25, 32)            5152      
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 25, 64)            10304     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 25, 32)            0         
Total params: 20,288
Trainable params: 20,288
Non-trainable params: 0
_________________________________________________________________
None


In [18]:
import keras.backend as K
channels = 5
steps = 4
filters = 3
val = np.array([list(range(i * channels, (i + 1) * channels)) for i in range(1, steps + 1)])
val = np.expand_dims(val, axis=0)
x = K.variable(value=val)

In [19]:
xtr = K.variable(value=X_train)

In [20]:
xtr.shape

TensorShape([Dimension(5500), Dimension(25), Dimension(30)])

In [21]:
xte = K.variable(value=X_test)

In [22]:
xte.shape

TensorShape([Dimension(1087), Dimension(25), Dimension(30)])

In [23]:
m1 = Conv1D(32, kernel_size=5, input_shape=(X_train.shape[1],X_train.shape[2]), activation='tanh', padding='same',data_format="channels_last")(xtr)
m1 = Conv1D(32, 5, activation='tanh', padding='same')(m1)
m1 = Conv1D(64, 5, activation='tanh', padding='same')(m1)
m1 = MaxPooling1D(pool_size=2, data_format="channels_first")(m1)

In [24]:
import keras.backend as K
w = K.eval(m1)

In [25]:
display(w[0][0])
X_train[0][0]

array([ 0.13772288,  0.1440878 , -0.04737678,  0.04508604, -0.2054001 ,
       -0.2243628 ,  0.20791698,  0.18870057, -0.00451072,  0.26015148,
        0.01376376,  0.3188596 ,  0.06905152,  0.13065755,  0.17002483,
       -0.20316277, -0.0772203 , -0.07744997,  0.21055119,  0.12976466,
       -0.09389918,  0.32234767,  0.22481084,  0.14570995, -0.14591041,
       -0.10086812, -0.1971597 ,  0.05255187, -0.10787158,  0.34776008,
        0.10903239,  0.16009106], dtype=float32)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.06060606, 0.        , 0.01343284, 0.22073579, 1.        ,
       0.25      , 0.11111111, 0.        , 0.48644338, 0.50615114,
       0.43425076, 0.        , 0.27926421, 0.02637363, 0.77966102,
       0.42574257, 0.46706587, 0.08112211, 0.10311573, 0.14356436,
       0.99009901, 0.44548872, 0.        , 0.02173913, 0.        ])

In [26]:
w.shape

(5500, 25, 32)

In [27]:
m2 = Conv1D(32, kernel_size=5, input_shape=(X_train.shape[1],X_train.shape[2]), activation='tanh', padding='same',data_format="channels_last")(xte)
m2 = Conv1D(32, 5, activation='tanh', padding='same')(m2)
m2 = Conv1D(64, 5, activation='tanh', padding='same')(m2)
m2 = MaxPooling1D(pool_size=2, data_format="channels_first")(m2)

In [28]:
p = K.eval(m2)

In [29]:
p.shape

(1087, 25, 32)

In [30]:
display(p[0][0])
X_test[0][0]

array([-0.08071789,  0.00882319,  0.09292839,  0.00201486,  0.05256507,
       -0.0402436 , -0.01839525,  0.02480232,  0.04182158,  0.08714173,
        0.0078541 ,  0.0109094 ,  0.00276865,  0.00259749, -0.00283157,
        0.03786698,  0.08089605,  0.00860622, -0.02711594,  0.0153498 ,
        0.0054774 ,  0.04707955,  0.05701359,  0.00357918,  0.07839356,
       -0.00435886, -0.03395067,  0.00527446, -0.0182531 ,  0.04238188,
       -0.03839114,  0.11150566], dtype=float32)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08585859, 0.        , 0.01641791, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.45869947,
       0.        , 0.11428571, 0.        , 0.02747253, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.24752475,
       0.        , 0.        , 0.        , 0.03024575, 0.        ])

In [31]:
w.shape

(5500, 25, 32)

In [32]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [33]:
Xd = K.variable(value=w)

In [34]:
Xd.shape

TensorShape([Dimension(5500), Dimension(25), Dimension(32)])

In [35]:
data = Sequential()(Xd)
data = LSTM(100, input_shape=(X_train.shape[1],X_train.shape[2]))(data)
data

<tf.Tensor 'lstm_1/TensorArrayReadV3:0' shape=(5500, 100) dtype=float32>

In [36]:
data.shape

TensorShape([Dimension(5500), Dimension(100)])

In [37]:
datap = K.eval(data)
datap

array([[ 0.03369261, -0.1366329 , -0.084447  , ...,  0.11716078,
        -0.00560257,  0.00019253],
       [ 0.01842513, -0.13861036, -0.10228729, ...,  0.10706023,
        -0.01226484,  0.00647754],
       [ 0.01643101, -0.08746438, -0.07659214, ...,  0.11347324,
         0.00647269, -0.03632727],
       ...,
       [-0.01126321, -0.03993411, -0.00913798, ...,  0.02303208,
        -0.0322965 , -0.00983312],
       [-0.00658668, -0.03266061, -0.00596168, ...,  0.01722318,
        -0.02531593, -0.00724855],
       [-0.00728277, -0.03582968,  0.00068842, ...,  0.01675329,
        -0.03178243, -0.01396135]], dtype=float32)

In [38]:
datap.shape

(5500, 100)

In [40]:
datab = LSTM(100, input_shape=(X_train.shape[1],X_train.shape[2]),return_sequences=True)(Xd)
datab = Bidirectional(LSTM(25),merge_mode='sum')(datab)

array([[[ 1.37722880e-01,  1.44087806e-01, -4.73767817e-02, ...,
          3.47760081e-01,  1.09032393e-01,  1.60091057e-01],
        [ 7.41634369e-02,  1.84784204e-01, -6.32183105e-02, ...,
          4.38126326e-01,  1.69678152e-01,  8.06098208e-02],
        [-1.73699390e-02,  8.04873928e-02,  1.53519124e-01, ...,
          4.46928322e-01,  2.53896892e-01,  3.87782037e-01],
        ...,
        [ 5.52381091e-02,  5.92302270e-02,  1.27111524e-01, ...,
          3.60848218e-01,  3.44443083e-01,  5.01371145e-01],
        [ 2.84323364e-01,  5.83044030e-02,  3.24828893e-01, ...,
          1.60399795e-01,  4.37611938e-01,  2.88239032e-01],
        [ 1.34732872e-01, -2.36551538e-02,  1.76956803e-01, ...,
          3.73298787e-02,  4.78230268e-01,  1.36108130e-01]],

       [[ 1.32037461e-01,  1.71968877e-01, -9.95918289e-02, ...,
          3.43061835e-01,  9.13972631e-02,  1.49748266e-01],
        [ 7.35678598e-02,  2.22585484e-01, -9.99128893e-02, ...,
          5.00170231e-01,  1.69328406e